apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: simple-mvcboot
  name: simple-mvcboot
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-mvcboot
    spec:
      containers:
        -
          image: sme/simple-mvc-boot:0.1
          name: simple-mvcboot
          ports:
            -
              containerPort: 8040
              name: http
