# Use simple-mvcboot-pod.yaml in dev environment only.
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: simple-mvcboot
  name: simple-mvcboot
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-mvcboot
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-mvcboot
    spec:
      containers:
        - image: sme/simple-mvc-boot:0.1
          name: simple-mvcboot
          ports:
            -
              containerPort: 8085
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 45
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 1Mi
            limits:
              memory: 1Mi            